// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXYUYtoH-I8bYMe0ccf5YhpFPNqVpFZI8',
    appId: '1:337173890721:web:5bb336ead0b0106314d2e0',
    messagingSenderId: '337173890721',
    projectId: 'pathfit-capstone-515e3',
    authDomain: 'pathfit-capstone-515e3.firebaseapp.com',
    storageBucket: 'pathfit-capstone-515e3.firebasestorage.app',
    databaseURL: 'https://pathfit-capstone-515e3-default-rtdb.firebaseio.com',

  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXYUYtoH-I8bYMe0ccf5YhpFPNqVpFZI8',
    appId: '1:337173890721:android:5bb336ead0b0106314d2e0',
    messagingSenderId: '337173890721',
    projectId: 'pathfit-capstone-515e3',
    storageBucket: 'pathfit-capstone-515e3.firebasestorage.app',
    databaseURL: 'https://pathfit-capstone-515e3-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXYUYtoH-I8bYMe0ccf5YhpFPNqVpFZI8',
    appId: '1:337173890721:ios:5bb336ead0b0106314d2e0',
    messagingSenderId: '337173890721',
    projectId: 'pathfit-capstone-515e3',
    storageBucket: 'pathfit-capstone-515e3.firebasestorage.app',
    iosBundleId: 'com.example.pathfitcapstone',
    databaseURL: 'https://pathfit-capstone-515e3-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXYUYtoH-I8bYMe0ccf5YhpFPNqVpFZI8',
    appId: '1:337173890721:macos:5bb336ead0b0106314d2e0',
    messagingSenderId: '337173890721',
    projectId: 'pathfit-capstone-515e3',
    storageBucket: 'pathfit-capstone-515e3.firebasestorage.app',
    iosBundleId: 'com.example.pathfitcapstone',
    databaseURL: 'https://pathfit-capstone-515e3-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXYUYtoH-I8bYMe0ccf5YhpFPNqVpFZI8',
    appId: '1:337173890721:windows:5bb336ead0b0106314d2e0',
    messagingSenderId: '337173890721',
    projectId: 'pathfit-capstone-515e3',
    storageBucket: 'pathfit-capstone-515e3.firebasestorage.app',
    databaseURL: 'https://pathfit-capstone-515e3-default-rtdb.firebaseio.com',
  );
}
